In [1]:
import numpy as np

In [30]:
A = [[1,2,3],
     [1,3,1],
     [1,4,0]]
A = np.array(A)
print(A)

[[1 2 3]
 [1 3 1]
 [1 4 0]]


In [31]:
I = np.identity(3)
T = [[1,0,0],
     [-1,1,0],
     [-1,0,1]]
print(np.dot(T,A))

[[ 1  2  3]
 [ 0  1 -2]
 [ 0  2 -3]]
